### ISSUE TITLE
Is this your implementation for LLMCompiler?

### ISSUE THREAD

**Issue by valentinvieriu** [phucdoan2003/chatbot-backend#1]
I was looking for a langgraph interpretation of LLMCompiler. Is this your version? Did you implement it yourself?
Are there any significant changes from the original?

**Comment by phucdoan2003** [comment]
Yes, it's the LLMcompiler with tavily and supabase vectorstore. I implemented it myself for learning so the folder structure is kinda all over the place.

**Comment by phucdoan2003** [comment]
I think I only add supabase to the original, everything else is the same.

**Comment by valentinvieriu** [comment]
This is perfect. I wanted to use this approach too but I've not found any JS implementation, only Python. I was about to convert it but then found your repo. Thank you for sharing the code!

Any feedback regarding performance? In the past I was using [REWoo ](https://arxiv.org/abs/2305.18323) but thinking on trying something that hopefully is faster. REWOO is quite serial when calling tools

**Comment by valentinvieriu** [comment]
> Yes, it's the LLMcompiler with tavily and supabase vectorstore. I implemented it myself for learning so the folder structure is kinda all over the place.

I'm also new to langgraph and was looking for a reference implementation ( and maybe folder structure)

Thank you again for sharing. I'll watch your repository if you decide to change it and find a better structure

**Comment by phucdoan2003** [comment]
I've only done basic plan and execute and this one, haven't tried REWoo yet. 

You should try to limit token usage (maybe limit replans), LLMCompiler loops quite a bit until it gives you the answer. Performance-wise it takes a lot longer than the basic plan and execute one, again because of the replans.

For the structure I would just change it to the nestjs structure with controller-service-module for each feature.
